[INFORMATION]
[TITLE]
[AUTHOR]
[SOURCE]DVD-lab
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&HFFFFFF,[STYLE]bd,[SIZE]32,[FONT]Nazanin
00:00:00.00,00:00:02.46
«ò‰Ê‰ œ— «Ì‰ »—‰·„Â

00:00:02.96,00:00:07.06
 « ›—œ« Â„êÌ

00:00:07.73,00:00:10.50
«·›»«

00:00:11.03,00:00:16.20
çÃÕŒÂ⁄€›ﬁÀ’÷

00:00:17.13,00:00:19.80
‘”Ì»·« ‰„òê

00:00:20.83,00:00:24.00
Ÿÿ“—–œ∆Ê

